package com.serverless.dal;

import java.time.LocalDate;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.fasterxml.jackson.databind.JsonNode;

public class Form {
	
	 private String id;
	 private String name;
	 private String creationDate;
	 private String description;
	 // time to fill the form in minutes
	 private int time;
	 
	 private Logger logger = LogManager.getLogger(this.getClass());
	 
	 public Form() {
		logger.info("Call Form::constructor");
		this.id = null;
		this.name = null;
		this.description = null;
		this.time = 0;
		this.creationDate = this.getCurrentTimeString();
	}
	 
	 public Form(JsonNode body) {
		 	logger.info("Call Form constructor(JsonNode)");
			this.id = body.get("id").asText();
			this.name = body.get("name").asText();
			this.description = body.get("description").asText();
			this.time = body.get("time").asInt();
			this.creationDate = this.getCurrentTimeString();
		}
	
	 
	 public void update(JsonNode body) {
		 logger.info("Call Form::update(" + body + ")");
		 JsonNode newName = body.get("name");
		 JsonNode newDescription = body.get("description");
		 JsonNode newTime = body.get("time");
		 
		 if(newName != null) {
			 this.setName(newName.asText());
		 }
		 else {
			 logger.warn("Name is null");
		 }
		 
		 if(newDescription != null) {
			 this.setDescription(newDescription.asText());
		 }
		 else {
			 logger.warn("Description is null");
		 }
		 
		 if(newTime != null) {
			 this.setTime(newTime.asInt());
		 }
		 else {
			 logger.warn("Time is null");
		 }
	 }
	 
	 	@DynamoDBHashKey(attributeName = "id")
	    @DynamoDBAutoGeneratedKey
	    public String getId() {
	 		logger.info("Call Form::getId() -> " + this.id);
	 		return this.id;
	    }
	 	
	    public void setId(String id) {
	    	logger.info("Call Form::setId(" + id + ")");
	        this.id = id;
	    }

	    @DynamoDBAttribute(attributeName = "name")
	    public String getName() {
	    	logger.info("Call Form::getName() -> " + this.name);
	    	return this.name;
	    }
	    
	    public void setName(String name) {
	    	logger.info("Call Form::setName(" + name + ")");
	    	this.name = name;
	    }

	    @DynamoDBAttribute(attributeName = "creationDate")
	    public String getCreationDate() {
	    	logger.info("Call Form::getCreationDate() -> " + this.creationDate);
	    	return this.creationDate;
	    }
	    
	    @DynamoDBAttribute(attributeName = "description")
	    public String getDescription() {
	    	logger.info("Call Form::getDescription() -> " + this.description);
	    	return this.description;
	    }
	    
	    public void setCreationDate(String creationDate) {
	    	logger.info("Call Form::setCreationDate(" + creationDate + ")");
	    	this.creationDate = creationDate;
	    }
	    
	    public void setDescription(String description) {
	    	logger.info("Call Form::setDescription(" + description + ")");
	    	this.description = description;
	    }
	    
	    @DynamoDBAttribute(attributeName = "time")
	    public int getTime() {
	    	logger.info("Call Form::getTime() -> " + this.time);
	    	return this.time;
	    }
	    
	    public void setTime(int time) {
	    	logger.info("Call Form::setTime(" + time + ")");
	    	this.time = time;
	    }
	    
	    private String getCurrentTimeString() {
	    	return LocalDate.now().toString();
	    }
	    
	    
	    
	    @Override
		public String toString() {
			return "Form [id=" + this.getId() + ", name()=" + this.getName() + ", creationDate()=" + this.getCreationDate() + 
					", description()" + this.getDescription() + ", time=" + this.getId() + "]";
		}

}
