package com.serverless.dal;

import java.util.HashMap;
import java.util.Map;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;

@DynamoDBTable(tableName = "SolvedForms-dev")
public class SolvedForm {
	
	private String id;
	private String formId;
	private String userId;
	private HashMap<String, String> userAnswers;
	
	private Logger logger = LogManager.getLogger(this.getClass());
	
	public SolvedForm() {
		logger.info("Call SolvedForm::constructor");
		this.id = null;
		this.formId = null;
		this.userId = null;
		this.userAnswers = null;
	}
	
	public SolvedForm(JsonNode body) {
		logger.info("Call SolvedForm::constructor(JsonNode)");
		this.formId = body.get("formId").asText();
		this.userId = body.get("userId").asText();
		this.userAnswers = new HashMap<String, String>();
		ObjectMapper mapper = new ObjectMapper();
		this.userAnswers = mapper.convertValue(body.get("userAnswers"), HashMap.class);
		 
	}
	
	@DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
	public String getId() {
		logger.info("Call SolvedForm::getId()");
		return this.id;
	}
	
	public void setId(String id) {
		logger.info("Call SolvedForm::setId(" + id +  ")");
		this.id = id;
	}
	
	@DynamoDBAttribute(attributeName = "formId")
	public String getFormId() {
		logger.info("Call SolvedForm::getFormId()");
		return this.formId;
	}
	
	public void setFormId(String formId) {
		logger.info("Call SolvedForm::setFormId(" + formId +  ")");
		this.formId = formId;
	}
	
	@DynamoDBAttribute(attributeName = "userId")
	public String getUserId() {
		logger.info("Call SolvedForm::getUserId()");
		return this.userId;
	}
	
	public void setUserId(String userId) {
		logger.info("Call SolvedForm::setUserId(" + userId +  ")");
		this.userId = userId;
	}
	
	@DynamoDBAttribute(attributeName = "userAnswers")
	public HashMap<String, String> getUserAnswers() {
		logger.info("Call SolvedForm::getUserAnswers()");
		return this.userAnswers;
	}
	
	public void setUserAnswers(HashMap<String, String> userAnswers) {
		logger.info("Call SolvedForm::setUserAnswers(" + userAnswers +  ")");
		this.userAnswers = userAnswers;
	}
	

}
