package com.serverless.dal;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;

public class ClosedQuestion  {
	 	private String id;
	    private String name;
	    private String question;
	    private String form_membership;
	    private String correct_answer;
	    private String wrong_answer1;
	    private String wrong_answer2;
	    private String wrong_answer3;
	    private String type="closed";
	    
	    
	    



		@DynamoDBHashKey(attributeName = "id")
	    @DynamoDBAutoGeneratedKey
		public String getId() {
			return id;
		}
		public void setId(String id) {
			this.id = id;
		}
		
		@DynamoDBRangeKey(attributeName = "name")
		public String getName() {
			return name;
		}
		
		public void setName(String name) {
			this.name = name;
		}
		
		@DynamoDBAttribute(attributeName = "question")
		public String getQuestion() {
			return question;
		}
		
		public void setQuestion(String question) {
			this.question = question;
		}
		
		
	    
		@DynamoDBAttribute(attributeName = "form_membership")
		public String getForm_membership() {
			return form_membership;
		}
		public void setForm_membership(String form_membership) {
			this.form_membership = form_membership;
		}


		@DynamoDBAttribute(attributeName = "correct_answer")
	    public String getCorrect_answer() {
			return correct_answer;
		}
		public void setCorrect_answer(String correct_answer) {
			this.correct_answer = correct_answer;
		}
		@DynamoDBAttribute(attributeName = "wrong_answer1")
		public String getWrong_answer1() {
			return wrong_answer1;
		}
		public void setWrong_answer1(String wrong_answer1) {
			this.wrong_answer1 = wrong_answer1;
		}
		@DynamoDBAttribute(attributeName = "wrong_answer2")
		public String getWrong_answer2() {
			return wrong_answer2;
		}
		public void setWrong_answer2(String wrong_answer2) {
			this.wrong_answer2 = wrong_answer2;
		}
		@DynamoDBAttribute(attributeName = "wrong_answer3")
		public String getWrong_answer3() {
			return wrong_answer3;
		}
		
		public void setWrong_answer3(String wrong_answer3) {
			this.wrong_answer3 = wrong_answer3;
		}
		
		@DynamoDBAttribute(attributeName = "type")
		public String getType() {
			return type;
		}
}
