package com.serverless.dal;

import com.amazonaws.services.dynamodbv2.AmazonDynamoDB;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapper;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapperConfig;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapperConfig.TableNameOverride;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBQueryExpression;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBScanExpression;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.PaginatedQueryList;
import com.amazonaws.services.dynamodbv2.model.AttributeValue;
import com.amazonaws.services.lambda.runtime.LambdaLogger;

import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import org.apache.logging.log4j.Logger;
import com.serverless.dal.DynamoDBAdapter;

@DynamoDBTable(tableName = "PLACEHOLDER_PRODUCTS_TABLE_NAME")
public class Question {

private static final String QUESTIONS_TABLE_NAME = System.getenv("QUESTIONS_TABLE_NAME");
    
    private static DynamoDBAdapter db_adapter;
    private final AmazonDynamoDB client;
    private final DynamoDBMapper mapper;


    private String id;
    private String name;
    private String question;
    private String form_membership;
    

    
    
    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
	
	@DynamoDBRangeKey(attributeName = "name")
	public String getName() {
		return name;
	}
	
	public void setName(String name) {
		this.name = name;
	}
	
	@DynamoDBAttribute(attributeName = "question")
	public String getQuestion() {
		return question;
	}
	
	public void setQuestion(String question) {
		this.question = question;
	}
	
	
    
	@DynamoDBAttribute(attributeName = "form_membership")
	public String getForm_membership() {
		return form_membership;
	}
	public void setForm_membership(String form_membership) {
		this.form_membership = form_membership;
	}
    
	

	public Question() {
	        // build the mapper config
	        DynamoDBMapperConfig mapperConfig = DynamoDBMapperConfig.builder()
	            .withTableNameOverride(new DynamoDBMapperConfig.TableNameOverride(QUESTIONS_TABLE_NAME))
	            .build();
	        // get the db adapter
	        this.db_adapter = DynamoDBAdapter.getInstance();
	        this.client = this.db_adapter.getDbClient();
	        // create the mapper with config
	        this.mapper = this.db_adapter.createDbMapper(mapperConfig);
	}
	
	   public List<Question> list() throws IOException {
	    	DynamoDBScanExpression scanExp = new DynamoDBScanExpression();
	        List<Question> results = this.mapper.scan(Question.class, scanExp);
	        return results;
	    }

	
	    
	
	public String toString() {
        return String.format("Product [id=%s, name=%s, question=$%f]", this.id, this.name, this.question);
    }
	
	// methods
    public Boolean ifTableExists() {
        return this.client.describeTable(QUESTIONS_TABLE_NAME).getTable().getTableStatus().equals("ACTIVE");
    }
    
 
    public Question get(String id) throws IOException {
    	Question question = null;

        HashMap<String, AttributeValue> av = new HashMap<String, AttributeValue>();
        av.put(":v1", new AttributeValue().withS(id));

        DynamoDBQueryExpression<Question> queryExp = new DynamoDBQueryExpression<Question>()
            .withKeyConditionExpression("id = :v1")
            .withExpressionAttributeValues(av);

        PaginatedQueryList<Question> result = this.mapper.query(Question.class, queryExp);
        if(result.size() > 0) {
        	question = result.get(0);
        }
        return question;
    }
    
  
    
    public  List<Question> getFormQuestions(String formid) throws IOException {
    	DynamoDBScanExpression scanExp = new DynamoDBScanExpression();
        List<Question> results = this.mapper.scan(Question.class, scanExp);
        List<Question> res = new ArrayList<Question>();
        for (int i=0; i< results.size(); i++)
        {
        	if (results.get(i).getForm_membership()!=null) {
        	if(results.get(i).getForm_membership().equals(formid))
        	{
        		res.add(results.get(i));
        	}
        	}
        }
        
        
        return res;
    }
    
    public  Boolean deleteQuestionFromForm(String questionid) throws IOException {
    	Question question = null;

        HashMap<String, AttributeValue> av = new HashMap<String, AttributeValue>();
        av.put(":v1", new AttributeValue().withS(questionid));

        DynamoDBQueryExpression<Question> queryExp = new DynamoDBQueryExpression<Question>()
            .withKeyConditionExpression("id = :v1")
            .withExpressionAttributeValues(av);

        PaginatedQueryList<Question> result = this.mapper.query(Question.class, queryExp);
        if (result.size() > 0) {
        	question = result.get(0);

        }
        
        question.setForm_membership(null);
        this.mapper.save(question);
        
        return true;
    }
    
    public  Boolean createMembership(String questionid, String formid) throws IOException {
    	Question question = null;

        HashMap<String, AttributeValue> av = new HashMap<String, AttributeValue>();
        av.put(":v1", new AttributeValue().withS(questionid));

        DynamoDBQueryExpression<Question> queryExp = new DynamoDBQueryExpression<Question>()
            .withKeyConditionExpression("id = :v1")
            .withExpressionAttributeValues(av);

        PaginatedQueryList<Question> result = this.mapper.query(Question.class, queryExp);
        if (result.size() > 0) {
        	question = result.get(0);

        }
        
        question.setForm_membership(formid);
        this.mapper.save(question);
        
        return true;
    }
    
    
    public  ClosedQuestion setCorrectAnswerr(String questionid, String answer) throws IOException {
    	ClosedQuestion closed = null;

        HashMap<String, AttributeValue> av = new HashMap<String, AttributeValue>();
        av.put(":v1", new AttributeValue().withS(id));

        DynamoDBQueryExpression<ClosedQuestion> queryExp = new DynamoDBQueryExpression<ClosedQuestion>()
            .withKeyConditionExpression("id = :v1")
            .withExpressionAttributeValues(av);

        PaginatedQueryList<ClosedQuestion> result = this.mapper.query(ClosedQuestion.class, queryExp);
        if(result.size() > 0) {
        	closed = result.get(0);
        }
        closed.setCorrect_answer(answer);
       return closed;
    }
    
    
    
    
    
    public void save(Question newquestion) throws IOException {
        this.mapper.save(newquestion);
    }
    
    public void save(Task task) throws IOException {
        this.mapper.save(task);
    }
    
    public void save(ClosedQuestion cq) throws IOException {
        this.mapper.save(cq);
    }
    
    public Boolean delete(String id) throws IOException {
    	Question question = null;

        // get product if exists
    	question = get(id);
        if (question != null) {
          this.mapper.delete(question);
        } 
        
        return true;
    }
    
}